<?php

/*
 * Hook menu
 */
function htn_menu() {
  $items['play-game'] = array(
    'title' => '',
    'description' => 'Game',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('htn_multistep_game_form'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}


/*
 * Implement hook_form_after
 */
function htn_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'gaming_node_form') {
    
    drupal_add_js(drupal_get_path('module', 'htn') . '/js/gaming.js');
    drupal_add_css(drupal_get_path('module', 'htn') . '/css/gaming.css');
    
    $form_state['rebuild'] = TRUE;
    
    global $base_url;
    $data = [];
    $request = drupal_http_request($base_url . '/' . drupal_get_path('module', 'htn') . '/data.json');
    $data = drupal_json_decode($request->data);
    $alter_steps = ['step_select_case_1','step_select_case_2','step_select_case_3'];
    $state = isset($form_state['values']['field_situation']['und'][0]['value']) ? $form_state['values']['field_situation']['und'][0]['value'] : '';
    $gender = isset($form_state['values']['field_gender']['und'][0]['value']) ? $form_state['values']['field_gender']['und'][0]['value'] : '';
    $name = isset($form_state['values']['field_name']) ? '<span class="name">' . $form_state['values']['field_name']['und'][0]['value'] . '</span>' : '';
    $class_2nd = [];
    $chose_class_2nd = isset($form_state['values']['field_case1_selected']) ? $form_state['values']['field_case1_selected']['und'][0]['value'] : [];
    $class_3rd = [];
    $chose_class_3rd = isset($form_state['values']['field_case2_selected']) ? $form_state['values']['field_case2_selected']['und'][0]['value'] : [];
    
    if (isset($form_state['values']['field_gender'])) {
      // Add gender class to form
      $form['#attributes']['class'][] = $gender;
    }
    
    if ($form_state['storage']['step'] === 'step_fill_name') {
      $face = file_create_url(file_load($form_state['values']['field_gaming_image']['und'][0]['fid'])->uri);
      $body = file_create_url('public://model') . '/' . $gender . '.png';
      $form['field_name']['#prefix'] = '<div class="actor"><img class="face" src="' . $face . '" /><img class="body" src="' . $body . '" /></div>';
    }
    
    if ($form_state['storage']['step'] === 'step_select_situation') {
      $form['field_situation']['#prefix'] = '<div class="situa"><div class="fresh"></div><div class="hot"></div></div>';
    }
    
    
    if (isset($form_state['storage']) && in_array($form_state['storage']['step'], $alter_steps)) {
      //dsm($data);
      // Build class 1st
      if ($state == 'fresh') {
        $class_1st = [];
        foreach($data['fresh'] as $key => $value) {
          $class_1st[$key] = str_replace('$name', $name, $value['title']);
        }
        $form['field_case1'] = [
          '#type' => 'radios',
          '#title' => t('Case 1'),
          '#options' => $class_1st,
          '#description' => t(''),
          '#access' => TRUE,
          '#default_value' => $form_state['values']['field_case1_selected']['und'][0]['value'],
          '#prefix' => str_replace('$name', $name, '<div class="intro"><div class="hello">Xin chào $name </div>'
            . '<div class="desc">Khi $name được thanh lọc bên trong, $name sẽ tươi trẻ bên ngoài.'
            . '<br/>Khi $name tươi trẻ bên ngoài, $name sẽ:</div></div>')
        ];
        $form['#steps']['step_select_case_1']->children[] = 'field_case1';
        $form['#step_children']['field_case1'] = 'step_select_case_1';
      }
      
      // Build class 2nd
      if (!empty($form_state['values']['field_case1_selected']['und'][0]['value'])) {
        //$class_2nd = [];
        

        foreach($data['fresh'][$chose_class_2nd]['sub'] as $key => $value) {
          $class_2nd[$key] = str_replace('$name', $name, $value['title']);
        }
        $form['field_case2'] = [
          '#type' => 'radios',
          '#title' => t('Case 2'),
          '#options' => $class_2nd,
          '#description' => t(''),
          '#access' => TRUE,
          '#default_value' => $form_state['values']['field_case2_selected']['und'][0]['value'],
          '#prefix' => str_replace('$name', $name, '<div class="intro"><div class="hello">Xin chào $name </div>'
            . '<div class="desc">Khi $name được thanh lọc bên trong, $name sẽ tươi trẻ bên ngoài.'
            . '<br/>Khi $name tươi trẻ bên ngoài, $name sẽ:</div></div>')
        ];
        $form['#steps']['step_select_case_2']->children[] = 'field_case2';
        $form['#step_children']['field_case2'] = 'step_select_case_2';
      }
      
      // Build class 3rd
      if (!empty($form_state['values']['field_case2_selected']['und'][0]['value'])) {
//        $class_3rd = [];
//        $chose_class_3rd = $form_state['values']['field_case2_selected']['und'][0]['value'];

        foreach($data['fresh'][$chose_class_2nd]['sub'][$chose_class_3rd]['sub'] as $key => $value) {
          $class_3rd[$key] = str_replace('$name', $name, $value['title']);
        }
        $form['field_case3'] = [
          '#type' => 'radios',
          '#title' => t('Case 3'),
          '#options' => $class_3rd,
          '#description' => t(''),
          '#access' => TRUE,
          '#default_value' => $form_state['values']['field_case3_selected']['und'][0]['value'],
          '#prefix' => str_replace('$name', $name, '<div class="intro"><div class="hello">Xin chào $name </div>'
            . '<div class="desc">Khi $name được thanh lọc bên trong, $name sẽ tươi trẻ bên ngoài.'
            . '<br/>Khi $name tươi trẻ bên ngoài, $name sẽ:</div></div>')
        ];
        $form['#steps']['step_select_case_3']->children[] = 'field_case3';
        $form['#step_children']['field_case3'] = 'step_select_case_3';
      }
    }
    
    if ($form_state['storage']['step'] === 'step_complete') {
      if (empty($form_state['values']['title'])) {
        $form['title']['#default_value'] = $form_state['values']['field_name']['und'][0]['value'] . '-' . time();
      }
      
      $video_url = file_create_url('public://bgvideo') . '/' . $data['fresh'][$chose_class_2nd]['sub'][$chose_class_3rd]['sub'][$form_state['values']['field_case3_selected']['und'][0]['value']]['video'];
      $form['field_background_video']['und'][0]['value']['#default_value'] = $video_url;

    }
    
    dsm($form);
    dsm($form_state);
  }
}

/*
 * Implement hook_preprocess_page
 */
function htn_preprocess_page(&$vars) {
  if ($vars['directory'] == 'sites/default/themes/STARTERKIT') {
    drupal_add_js(drupal_get_path('module', 'htn') . '/js/nghia.js');
    drupal_add_css(drupal_get_path('module', 'htn') . '/css/nghia.css');
    
    if (isset($vars['node']->type)) {
      $vars['theme_hook_suggestions'][] = 'page__' . $vars['node']->type;
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function htn_theme_registry_alter(&$theme_registry) {
	// Defined path to the current module.
	$module_path = drupal_get_path('module', 'htn');
	// Find all .tpl.php files in this module's folder recursively.
	$template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
	// Iterate through all found template file objects.
	foreach ($template_file_objects as $key => $template_file_object) {
		// If the template has not already been overridden by a theme.
		if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
			// Alter the theme path and template elements.
			$theme_registry[$key]['theme path'] = $module_path;
			$theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
			$theme_registry[$key]['type'] = 'module';
		}
	}
}

/**
 * Implements hook_theme().
 */
function htn_theme($existing, $type, $theme, $path) {
 $theme = array();
 $theme['node__gaming'] = array(
   'render element' => 'content',
   'base hook' => 'node',
   'template' => 'node--gaming',
   'path' => drupal_get_path('module', 'htn') . '/templates',
  );
 return $theme;
}