<?php

/*
 * Implement hook_preprocess_page
 */
function mobile_preprocess_page(&$vars) {
  if ($vars['directory'] == 'sites/default/themes/mobile') {
    drupal_add_js(drupal_get_path('module', 'mobile') . '/js/nghia.js');
    drupal_add_css(drupal_get_path('module', 'mobile') . '/css/nghia.css');
    drupal_add_js(drupal_get_path('module', 'mobile') . '/js/mobile.js');
    drupal_add_css(drupal_get_path('module', 'mobile') . '/css/mobile.css');
    
    if (isset($vars['node']->type)) {
      $vars['theme_hook_suggestions'][] = 'page__' . $vars['node']->type;
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function mobile_theme_registry_alter(&$theme_registry) {
	// Defined path to the current module.
	$module_path = drupal_get_path('module', 'mobile');
	// Find all .tpl.php files in this module's folder recursively.
	$template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
	// Iterate through all found template file objects.
	foreach ($template_file_objects as $key => $template_file_object) {
		// If the template has not already been overridden by a theme.
		if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
			// Alter the theme path and template elements.
			$theme_registry[$key]['theme path'] = $module_path;
			$theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
			$theme_registry[$key]['type'] = 'module';
      //kpr($theme_registry);
		}
	}
}

/**
 * Implements hook_theme().
 */
function mobile_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['node__gaming'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--gaming',
    'path' => drupal_get_path('module', 'mobile') . '/templates',
  );
  $theme['node__story'] = array(
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--story',
    'path' => drupal_get_path('module', 'mobile') . '/templates',
  );
  return $theme;
}
