<?php

/*
 * Implement hook_preprocess_page
 */
function mobile_preprocess_page(&$vars) {
  if ($vars['directory'] == 'sites/default/themes/mobile') {
    if ($vars['is_front']) {
      drupal_goto('home');
    }
    
    drupal_add_css(drupal_get_path('module', 'mobile') . '/css/mobile.css');
    drupal_add_js(drupal_get_path('module', 'mobile') . '/js/mobile.js');
  }
}

/**
 * Implements template_preprocess_views_view_unformatted.
 */
function mobile_preprocess_views_view_unformatted(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'aseptic' && ($view->current_display == 'block' || $view->current_display == 'block_2') 
          || $view->name == 'bottle' && ($view->current_display == 'block')
          || $view->name == 'label' && ($view->current_display == 'block' || $view->current_display == 'block_2')) {
    $classes_array = $vars['classes_array'];
    $types = ['field_fix_background', 'field_drag_background', 'field_270_background'];
    foreach($classes_array as $key => $classes) {
      $bg_type = '';
      foreach($types as $type) {
        if (!empty($view->result[$key]->_field_data['nid']['entity']->$type)) {
          $bg_type = $type;
          break;
        }
      }
      if (!empty($view->result[$key]->_field_data['nid']['entity']->field_follow_with)) {
        $vars['classes_array'][$key] = $classes
                . ' aseptic nid-' . $view->result[$key]->_field_data['nid']['entity']->nid
                . ' follow follow-nid-' . $view->result[$key]->_field_data['nid']['entity']->field_follow_with['und'][0]['target_id']
                . ' ' . $bg_type;
      } 
      else {
        $vars['classes_array'][$key] = $classes . ' aseptic nid-' . $view->result[$key]->_field_data['nid']['entity']->nid . ' ' . $bg_type;
      }
    }
  }
}
